services:
  - type: web
    name: barbearia-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: FIREBASE_WEB_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FIREBASE_STORE_COLLECTION
        value: barbeariaApp
      - key: FIREBASE_STORE_DOC
        value: store
      - key: FIREBASE_WEB_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_WEB_PROJECT_ID
        sync: false
      - key: FIREBASE_WEB_APP_ID
        sync: false
      - key: FIREBASE_WEB_GOOGLE_CLIENT_ID
        sync: false
